import { useState, useEffect } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [next, setNext] = useState();
  const [nfts, setNfts] = useState([]);

  useEffect(() => {
    init();
  }, []);

  const init = async () => {
    const slug = 'basedpunks';
    const { data = {} } = await fetch(`/api/listed?slug=${slug}&next=${next}`).then(res => res.json());
    console.log(`${slug}: `, data);
    setNext(data?.next);
    setNfts(data?.nfts || []);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>OpenMeme, the largest NFT marketplace</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <nav className={styles.nav}>
        <h1 className={styles.title}>OpenMeme</h1>
        <ConnectButton />
      </nav>
      <main className={styles.main}>
        <div style={{ display: 'grid', gap: '16px', gridTemplateColumns: '1fr 1fr 1fr 1fr', width: '100%' }}>
          {nfts.map((nft: any, idx) => (
            <div
              key={nft?.identifier || idx}
              style={{
                display: 'flex',
                flexDirection: 'column',
                gap: '4px',
                margin: 'auto',
                cursor: 'pointer',
                border: '1px solid #333',
                borderRadius: '8px',
                width: '100%',
              }}
            >
              <img src={nft?.image_url} style={{ width: '100%', height: 'auto', maxWidth: '150px', margin: 'auto' }} />
              <p style={{ width: '100%', textAlign: 'center' }}>{nft?.name}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/jill6666/nft-marketplace" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
