import { useState, useEffect } from 'react';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [next, setNext] = useState();
  const [nfts, setNfts] = useState([]);

  useEffect(() => {
    init();
  }, []);

  const init = async () => {
    const slug = 'basedpunks';
    const { data = {} } = await fetch(`/api/listed?slug=${slug}&next=${next}`).then(res => res.json());
    console.log(`${slug}: `, data);
    setNext(data?.next);
    setNfts(data?.nfts || []);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>OpenMeme, the largest NFT marketplace</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <nav className={styles.nav}>
        <h1 className={styles.title}>OpenMeme</h1>
        <ConnectButton />
      </nav>
      <main className={styles.main}>
        <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>
          {nfts.map((nft: any, idx) => (
            <div key={nft?.identifier || idx}>
              <img src={nft?.image_url} style={{ width: '100px', height: '100px' }} />
              {nft?.name}
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://github.com/jill6666/nft-marketplace" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
